---
  - name: ELK config
    hosts: elkservers
    become: true
    tasks:
      - name: Install Docker
        apt:
          name: docker.io
          state: present

      - name: Install pip
        apt: 
          name: python-pip
          state: present

      - name: Install docker py module
        pip:
          name: docker
          state: present

      - name: System Memory Config
        shell: 
          cmd: sysctl -w vm.max_map_count=262144
 
      - name: Install the docker elk container
        docker_container:
          name: ELK
          image: sebp/elk
          state: started
          ports: 
           - "5601:5601"
           - "9200:9200"
           - "5044:5044"